"""added GameResults table

Revision ID: 3dbb746b7a2b
Revises: 806e838bd04c
Create Date: 2024-05-06 16:36:57.888211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbb746b7a2b'
down_revision = '806e838bd04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_id2', sa.Integer(), nullable=False),
    sa.Column('user_choice', sa.String(length=8), nullable=False),
    sa.Column('user_choice2', sa.String(length=8), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_results_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_results_user_id2'), ['user_id2'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_results_user_id2'))
        batch_op.drop_index(batch_op.f('ix_game_results_user_id'))

    op.drop_table('game_results')
    # ### end Alembic commands ###
