"""empty message

Revision ID: 4cbfb9e31e71
Revises: 3d06f8d25dd3
Create Date: 2024-05-15 05:18:38.680219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbfb9e31e71'
down_revision = '3d06f8d25dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_opponent_id'), ['opponent_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['opponent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_opponent_id'))
        batch_op.drop_column('opponent_id')

    # ### end Alembic commands ###
