"""challenge table

Revision ID: aaf64967ae42
Revises: 3dbb746b7a2b
Create Date: 2024-05-07 17:41:04.761362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf64967ae42'
down_revision = '3dbb746b7a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('challenger', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['accepted'], ['user.id'], ),
    sa.ForeignKeyConstraint(['challenger'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_accepted'), ['accepted'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_challenger'), ['challenger'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_challenger'))
        batch_op.drop_index(batch_op.f('ix_challenge_accepted'))

    op.drop_table('challenge')
    # ### end Alembic commands ###
